# Generated by Django 5.1.5 on 2025-09-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('parsed_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('parsed_text', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=20)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='screening.jobdescription')),
            ],
        ),
    ]
